/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as HesapRouteImport } from './routes/hesap'
import { Route as KosullarRouteImport } from './routes/kosullar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MagazaRouteImport } from './routes/magaza'
import { Route as OyunRouteImport } from './routes/oyun'
import { Route as ApiIceRouteImport } from './routes/api/ice'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiStoreNotifyRouteImport } from './routes/api/store-notify'
import { Route as OyunKurRouteImport } from './routes/oyun.kur'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const HesapRoute = HesapRouteImport.update({
  id: '/hesap',
  path: '/hesap',
  getParentRoute: () => rootRouteImport,
} as any)
const KosullarRoute = KosullarRouteImport.update({
  id: '/kosullar',
  path: '/kosullar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazaRoute = MagazaRouteImport.update({
  id: '/magaza',
  path: '/magaza',
  getParentRoute: () => rootRouteImport,
} as any)
const OyunRoute = OyunRouteImport.update({
  id: '/oyun',
  path: '/oyun',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIceRoute = ApiIceRouteImport.update({
  id: '/api/ice',
  path: '/api/ice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreNotifyRoute = ApiStoreNotifyRouteImport.update({
  id: '/api/store-notify',
  path: '/api/store-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const OyunKurRoute = OyunKurRouteImport.update({
  id: '/kur',
  path: '/kur',
  getParentRoute: () => OyunRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gizlilik': typeof GizlilikRoute
  '/hesap': typeof HesapRoute
  '/kosullar': typeof KosullarRoute
  '/login': typeof LoginRoute
  '/magaza': typeof MagazaRoute
  '/oyun': typeof OyunRouteWithChildren
  '/api/ice': typeof ApiIceRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/store-notify': typeof ApiStoreNotifyRoute
  '/oyun/kur': typeof OyunKurRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gizlilik': typeof GizlilikRoute
  '/hesap': typeof HesapRoute
  '/kosullar': typeof KosullarRoute
  '/login': typeof LoginRoute
  '/magaza': typeof MagazaRoute
  '/oyun': typeof OyunRouteWithChildren
  '/api/ice': typeof ApiIceRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/store-notify': typeof ApiStoreNotifyRoute
  '/oyun/kur': typeof OyunKurRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/gizlilik': typeof GizlilikRoute
  '/hesap': typeof HesapRoute
  '/kosullar': typeof KosullarRoute
  '/login': typeof LoginRoute
  '/magaza': typeof MagazaRoute
  '/oyun': typeof OyunRouteWithChildren
  '/api/ice': typeof ApiIceRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/store-notify': typeof ApiStoreNotifyRoute
  '/oyun/kur': typeof OyunKurRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/gizlilik'
    | '/hesap'
    | '/kosullar'
    | '/login'
    | '/magaza'
    | '/oyun'
    | '/api/ice'
    | '/api/rtc'
    | '/api/store-notify'
    | '/oyun/kur'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/gizlilik'
    | '/hesap'
    | '/kosullar'
    | '/login'
    | '/magaza'
    | '/oyun'
    | '/api/ice'
    | '/api/rtc'
    | '/api/store-notify'
    | '/oyun/kur'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/gizlilik'
    | '/hesap'
    | '/kosullar'
    | '/login'
    | '/magaza'
    | '/oyun'
    | '/api/ice'
    | '/api/rtc'
    | '/api/store-notify'
    | '/oyun/kur'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GizlilikRoute: typeof GizlilikRoute
  HesapRoute: typeof HesapRoute
  KosullarRoute: typeof KosullarRoute
  LoginRoute: typeof LoginRoute
  MagazaRoute: typeof MagazaRoute
  OyunRoute: typeof OyunRouteWithChildren
  ApiIceRoute: typeof ApiIceRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiStoreNotifyRoute: typeof ApiStoreNotifyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesap': {
      id: '/hesap'
      path: '/hesap'
      fullPath: '/hesap'
      preLoaderRoute: typeof HesapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosullar': {
      id: '/kosullar'
      path: '/kosullar'
      fullPath: '/kosullar'
      preLoaderRoute: typeof KosullarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magaza': {
      id: '/magaza'
      path: '/magaza'
      fullPath: '/magaza'
      preLoaderRoute: typeof MagazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyun': {
      id: '/oyun'
      path: '/oyun'
      fullPath: '/oyun'
      preLoaderRoute: typeof OyunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ice': {
      id: '/api/ice'
      path: '/api/ice'
      fullPath: '/api/ice'
      preLoaderRoute: typeof ApiIceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store-notify': {
      id: '/api/store-notify'
      path: '/api/store-notify'
      fullPath: '/api/store-notify'
      preLoaderRoute: typeof ApiStoreNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyun/kur': {
      id: '/oyun/kur'
      path: '/kur'
      fullPath: '/oyun/kur'
      preLoaderRoute: typeof OyunKurRouteImport
      parentRoute: typeof OyunRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OyunRouteChildren {
  OyunKurRoute: typeof OyunKurRoute
}

const OyunRouteChildren: OyunRouteChildren = {
  OyunKurRoute: OyunKurRoute,
}

const OyunRouteWithChildren = OyunRoute._addFileChildren(OyunRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GizlilikRoute: GizlilikRoute,
  HesapRoute: HesapRoute,
  KosullarRoute: KosullarRoute,
  LoginRoute: LoginRoute,
  MagazaRoute: MagazaRoute,
  OyunRoute: OyunRouteWithChildren,
  ApiIceRoute: ApiIceRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiStoreNotifyRoute: ApiStoreNotifyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
